### PR TITLE
bump netmask 1.0.6 => 2.0.1

### PR DESCRIPTION
**Pull request by juan-restrepo**
https://www.npmjs.com/advisories/1658

### CODE REVIEW

**Comment by rahulverma** [comment]
From what I can gather, netmask is only used [here](https://github.com/TooTallNate/node-pac-resolver/blob/925ba4c68a23d269551bd8ca04b8325adef0529b/src/isInNet.ts#L40). The update does not affect this line of code.

Can we please update this package?

**Comment by mfranzke** [comment]
Closes #26

**Comment by Tobi-mmt** [comment]
resolves #26 
Would be nice if this PR can be merged as soon as possible @TooTallNate

**Comment by juan-restrepo** [comment]
@TooTallNate can you please give this a go? Thank you!

**Comment by TooTallNate** [comment]
Thanks @juan-restrepo! Published in [`v4.1.1`](https://github.com/TooTallNate/node-pac-resolver/releases/tag/4.1.1).

**Pull request merged**
