### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by afetter**
upgraded degenerator package due dependency to vm2 which has a VULN

### CODE REVIEW

**Comment by afetter** [comment]
@TooTallNate, @RichardLitt, @utsavkesharwani, @Havunen 
Can you guys please approve this small change on this project. 
I found a VULN on degenerator@3.0.2 > vm2@3.9.13, upgrading `degenerator` to 3.0.4 will fix it. 

Thank you so much.

**Comment by TooTallNate** [comment]
This change is not necessary. The semver range is already loose enough to allow for this updated version of the dependency to be installed. Please just update your lockfile.

**Comment by afetter** [comment]
I'm curios about why you don't want to upgrade this package.
Can you explain it to me?

**Comment by TooTallNate** [comment]
Because there is no need to publish a new package version. If you install this module fresh, you will get the fixed version of `vm2` installed:

```
$ npm i pac-resolver

added 21 packages in 261ms

$ npm ls vm2
└─┬ pac-resolver@5.0.1
  └─┬ degenerator@3.0.4
    └── vm2@3.9.17
```

If you are not getting the fixed version, it's because your lockfile is preventing that from happening, in which case you need to run `npm upgrade` (or the equivalent for whichever package manager you are using).

**Pull request closed without merging**
