### PR TITLE
Up version to reflect patch

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks!

**Comment by RichardLitt** [comment]
No problem. Do you know if I can up the version for node-pac-resolver from a PR, or is that normally something the main contributor would do?

**Comment by TooTallNate** [comment]
I'd usually do that. I'll try to get to that at some point today.

On Sat, Feb 21, 2015 at 11:35 AM, Richard Littauer <notifications@github.com

**Comment by RichardLitt** [comment]
Cool. Thanks!

**Pull request merged**
